### ISSUE TITLE
[Tracking] First design

### ISSUE THREAD

**Issue by schettn** [snek-at/agt-guntrade-shop#4]
It is required to create wireframes and implement them for all necessary pages.

# Requirements (still shaping)
- Contact form (link or direct integration)
- The header of the landing page cannot be static. There must be dynamic content of some kind.
       

>  One solution would be a hybrid: 

            1. Featuring new products/sales/recommendations
            2. A slider (fixed slides of 3 or 4) containing Jaen TextFields to create dynamic texts.

# User Stories

- [ ] **(1)** As a visitor I want to see relevant products and categories at the site top. 
#5 
- [ ] **(2)** As a visitor I want to see products on sale. 
#5 
- [ ] **(3)** As a visitor I want to see new products. 
#5 
- [ ] **(4)** As a visitor I want to see upcoming events or news via notifications.
- [ ] **(5)** As a visitor I want to be able to communicate with the shop owner via a build in WhatsApp like chat.
- [ ] **(6)** As a visitor I want to follow social media channels of the company (instagram).
- [ ] **(7)** As a visitor I want to see embedded google reviews to get a glimpse into public opinions about the company.
- [ ] **(8)** As a visitor I want to send emails via a contact form.
- [ ] **(9)** As a visitor I want to see the company’s location on a map.
- [ ] **(10)** As a visitor I want to send emails via a contact form on specific products.
- [ ] **(11)** As a visitor I want to search for specific products
- [ ] **(12)** As a visitor I want to filter products
- [ ] **(13)** As a visitor I want to view a specific product to see general information like price, description, images, tags, etc…
- [ ] **(14)** As a entrepreneur visitor I want to register a new account.
- [ ] **(16)** As shop owner I want to tell the history of my company.
- [ ] **(17)** As shop owner I want to list the logos of my partners.
- [ ] **(18)** As shop owner I want to list news that are published on instagram.
- [ ] **(19)** As shop owner I want to establish my brand with a logo that is displayed on the top of the website.
- [ ] **(20)** As shop owner I want to establish my brand with a banner or header that I can use for mail traffic.

# Wireframe
![image](https://user-images.githubusercontent.com/52858351/139318099-a6045472-259c-45c3-a711-22d13c5e7986.jpeg)
